### ISSUE TITLE
#1009: Cannot access a property or method of a null object reference. error 

### ISSUE THREAD

**Issue by ajanslongplay** [myflashlab/zipManager-ANE#1]
Hi, i buy the zip manager product just now. but, when i use the extension, i get the Error #1009: Cannot access a property or method of a null object reference. error in _ex.addEventListener(ZipManagerEvent.COMPLETED,onComplete); line.

please help me,

thanks.

**Comment by myflashlab** [comment]
you probably have not seen our video courses. Check this playlist. these videos may help you: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
