### ISSUE TITLE
Unable to get zipManager to work

### ISSUE THREAD

**Issue by xs2bas** [myflashlab/zipManager-ANE#10]
I purchased the commercial vesion of zipManager, but can't get it to work, receiving this error:
```xml
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.dependency::OverrideAir()
	at com.myflashlab.air.extensions.dependency::OverrideAir$/applyToAneLab()
	at com.myflashlab.air.extensions.zip::ZipManager()
```
I did this import in my code:
```actionscript
import com.myflashlab.air.extensions.zip.ZipManager;
import com.myflashlab.air.extensions.dependency.OverrideAir;
```

Added this in my application-xml:
```xml
  <extensions>
	<extensionID>com.myflashlab.air.extensions.zipManager</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
  </extensions>
```
These files are added to the local library-path in Animate:
- zipManagerExtension.swc
- overrideAir.ane
- androidSupport-lite.ane
- zipManagerExtension.ane

... and ran this line:
```actionscript
var _ex:ZipManager = new ZipManager();
```
... so as basic as possible.

I receive the error when testing in AIR Debug Launcher (Mobile) using AIR-version 29 ...
What's going wrong?

**Comment by myflashlab** [comment]
This error simply means that the ANE is not correctly implemented in your project. This also happens if you are testing on a simulator.

**Comment by xs2bas** [comment]
Does this mean that when using the ZipManager-extension I cannot test the app in the simulator anymore? The ZipManager is only a small part of the app ... do I have to publish to an iPad for example to test all app-changes, even when not working on the ZipManager-part?

**Comment by myflashlab** [comment]
Closing the issue due to no response for a long time.
