### ISSUE TITLE
FileNotFoundException - java don't see the file

### ISSUE THREAD

**Issue by tudal** [myflashlab/zipManager-ANE#13]
## Environment ##
* Android API Version: 6.0.1
* AIR SDK Version: 30

## Problem Description ##
```xml
	<extensions>
		<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
		<extensionID>com.myflashlab.air.extensions.zipManager</extensionID>
	</extensions>
```

```actionscript
	public function start():void {
		_dir = File.applicationStorageDirectory.resolvePath('unzip');
		_downloader = new FileDownloaderSingle('http://10.0.0.5/TaernAS3www/', _dir.nativePath + '/');
		_downloader.readySignal.add(onDownoader1_Ready);
		_downloader.download(new FileInfo('extensions.zip\t1488198420\t1524586923350\t52444886'));
	}

	private function onDownoader1_Ready(downloader:FileDownloaderSingle):void {
		traceYellow("UnzipANETest.onDownloader1_Ready()  ");
		trace2('start unzip...');
		trace2('save in: ' + _dir.nativePath);
		_zipMan = new ZipManager();
		_zipMan.addEventListener(ZipManagerEvent.START, onStart);
		_zipMan.addEventListener(ZipManagerEvent.ERROR, onError);
		_zipMan.addEventListener(ZipManagerEvent.COMPLETED, onComplete);
		trace2('zip file path: ' + _downloader.file.nativePath);
		trace2('downloaded file size: ' + TextUtils.readablizeBytes(_downloader.file.size) + ' ' + _downloader.file.exists + ' ' + _downloader.file.name);
		_zipMan.unzip(_downloader.file, _dir);
	}

	private function onStart(e:ZipManagerEvent):void {
		trace("zip process started...");
	}

	private function onError(e:ZipManagerEvent):void {
		trace("zip process ERROR: " + e.param.msg);
	}

	private function onProgress(e:ZipManagerEvent):void {
		trace("zip Progress = " + e.param.perc + "%");
	}

	private function onComplete(e:ZipManagerEvent):void {
		trace("[zip process finished]");
	}
```

The trace I get is:
[trace] filePath: /data/user/0/air.TaernMobile/TaernMobile/Local Store/unzip/test.zip
[trace] UnzipANETest.onDownloader1_Ready()
[trace] start unzip...
[trace] save in: /data/user/0/air.TaernMobile/TaernMobile/Local Store/unzip
[trace] zip file path: /data/user/0/air.TaernMobile/TaernMobile/Local Store/unzip/test.zip
[trace] downloaded file size: 588.67 kb true test.zip
[trace] zip process started...
[trace] zip process ERROR: **java.io.FileNotFoundException**: /storage/emulated/0/data/user/0/air.TaernMobile/TaernMobile/Local Store/unzip/test.zip: open failed: ENOENT (No such file or directory)
[trace] [zip process finished]

So even If I see the file from AS3, see that it have some size,  ANE (JAVA) don't see it.
ANE you provided in previous issue don't fix this.

**Comment by myflashlab** [comment]
on Android, try using the ```File.documentsDirectory```. in your code, I see that you are using ```File.applicationStorageDirectory```.

However, we are doing some tests to make sure the zip ANE on Android can correctly does its job on other locations also. when our tests are finished, we'll update you.

**Comment by tudal** [comment]
File.documentsDirectory doesn't work on mobile...
Only File.applicationStorageDirectory and File.cacheDirectory are avaliable

**Comment by myflashlab** [comment]
> File.documentsDirectory doesn't work on mobile...

Why would you say that? Of course it does!

Anyhow, check this quick version. it should zip/unzip from ```File.applicationStorageDirectory```. Please confirm so we can finalize and release the new version. [zipManagerExtension.ane.zip](https://github.com/myflashlab/zipManager-ANE/files/2205064/zipManagerExtension.ane.zip)

**Comment by tudal** [comment]
I get File.documentsDirectory Error #3001: File or directory access denied.
Phone have SD card and I got 
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

Maybe you know some trick for that.

New ANE fixed the issue! Thanks!

Whats the procedure to get licensed version of this new ane (already bought)?

**Comment by myflashlab** [comment]
To have access to ```File.documentsDirectory``` you need the [permissionCheck ANE](https://github.com/myflashlab/PermissionCheck-ANE/). So your app can have access to the public location rather than your app's private location.

> Whats the procedure to get licensed version of this new ane (already bought)?

Thanks for confirming that the new version works. we will be releasing that in a few minutes through the [ANELAB](https://github.com/myflashlab/ANE-LAB/) channel. If you are a club member, you will have instance access to it. If not, you need to wait a few days before we can update the ANE manually.
