### ISSUE TITLE
 java.lang.IllegalArgumentException issue

### ISSUE THREAD

**Issue by OceanBreezeGames** [myflashlab/zipManager-ANE#14]
On my Android tablet I will get the following issue every once in a while when I go to unzip a package. Lots of times it does work, but sometimes the exception below is thrown.

> 11-12 01:39:05.131 799-799/? E/AndroidRuntime: FATAL EXCEPTION: main
>      Process: ... PID: 799
>      java.lang.IllegalArgumentException
>          at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
>          at com.doitflash.zipManager.AirCommand$2.onProgress(AirCommand.java:128)
>          at com.doitflash.zipManager.lib.UnzipTask.onProgressUpdate(Decompress.java:265)
>          at com.doitflash.zipManager.lib.UnzipTask.onProgressUpdate(Decompress.java:136)
>          at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:687)
>          at android.os.Handler.dispatchMessage(Handler.java:102)
>          at android.os.Looper.loop(Looper.java:154)
>          at android.app.ActivityThread.main(ActivityThread.java:6119)
>          at java.lang.reflect.Method.invoke(Native Method)
>          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

I have a suspicion that it occurs when I try and unzip 2 zipped files at the same time and dispose one of them before the other is done. Any ideas if that would cause this issue?

**Comment by OceanBreezeGames** [comment]
I may have solved this. I now queue the unzipping process and only unzip one package at a time. Doesn't seem to crash now from what I can tell in my testing so far.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
