### ISSUE TITLE
Error Opening ZIP file in applicationDirectory (Android 5.0.1)

### ISSUE THREAD

**Issue by syberkitten** [myflashlab/zipManager-ANE#3]
Hi
having a problem loading a file from applicationDirectory on Android.
Since applicationDirectory is returned empty.

The only way to load an asset bundled with the APK is to resolve
a File path but load using URLLoader since nativePath is not available.

when running the zip manager ANE: i get the following error:
zip process ERROR: java.io.FileNotFoundException: /storage/emulated/0: open failed: EISDIR (Is a directory)

I'm passing a File instance that is actually resolved to a zip file inside applicationDirectory.
It can be loaded using a URLLoader class, and the File reference returns true for both .exists / .size
but We cannot loaded it using nativePath.

the files in that folder are protected / hidden, so it's not even possible
to see the listings inside.

I succeed loading the file manually (not using this extension), that is using the .url property of the File instance.

If this ANE would allow unzipping from a ByteArray instance, It would solve the issue.

Or even better, load the zip asset using .url property as fallback and not only nativePath.

so it can look like this:

option A.
- loading the zip file via AS3 URLLoader -> ByteArray
- passing the ByteArray to zipmanager and output folder.

option B
- zipMananger loads File using .url property same as URLLoader does.

some technical specs:
Using AIR SDK 21
Android 5.0.1 - On Lenovo TAB 2 A10-70F
Kernel version - 3.10.61

**Comment by syberkitten** [comment]
more useful info?

The zip Asset is packaged into the APK same as the Icons for the Application,
difference is that the zip does not need to also be reflected inside the manifest xml.

Since i know the filename for the zip It can be resolved usinng File.resolvePath
but when accessing the nativePath, it's empty.

So i can load the file in two ways:
1. using URLLoader and .url property of the File instance
2. using FileStream (which receives a File instance)

**Comment by myflashlab** [comment]
We are issuing an update on this extension which will solve a lot of path related issues on Android. I will notify you here as soon as the new version is released. Thanks.

**Comment by syberkitten** [comment]
Also wondering, about other good practices to include image assets
within an APK?

Two of my approaches, after doing some research:
1. include a zip, unpack it in as3 on the device, and save
the assets locally on the device.
2. include each asset separately, then copy the assets to
the proper directory by as3 code on the device.

**Comment by syberkitten** [comment]
any news about the update? 👍

**Comment by myflashlab** [comment]
Please update to the latest version and the ANE now also works with ```File.applicationStorageDirectory```. Not *applicationDirectory*.

> If this ANE would allow unzipping from a ByteArray instance

This is in contrast with the main reason that this ANE was designed for. zipping and extracting zip files is already available with pure AS3 libraries but the difference is that this ANE does the job in background meaning that zip file bytes will never be loaded all into runtime. This behavior guarantees that you can un/zip BIG files without worrying about your AIR app running our of memory. And besides, it's native operation does the job super fast. So fast that it cannot be compared with the AS3 solutions at all.
