### ISSUE TITLE
Android unzip error

### ISSUE THREAD

**Issue by varadig** [myflashlab/zipManager-ANE#4]
on iOS is working, but on Android is not wirking the unzip.
I got this error message:
zip process ERROR: java.io.FileNotFoundException: /mnt/sdcard/ac/pages/page_01.xml: open failed: ENOENT (No such file or directory)

this is how I wanted to unzip:

```
 public function uncompressFile(from:File, to:File):void {
        this.reader.unzip(from, to);
    }
```
the from is:
`File.documentsDirectory.resolvePath("ac_temp/content.zip")`
the to is:
`File.documentsDirectory.resolvePath("ac");`

the log:

```
[trace] 2016-7-28 6_22_17_223 ----> start download content
[trace] 2016-7-28 6_22_17_243 ----> uncompressed content is not exist
[trace] 2016-7-28 6_22_17_262 ----> zipped content is exist
[trace] 2016-7-28 6_22_17_284 ----> content archive is downloaded!
[trace] 2016-7-28 6_22_17_306 ----> archive size:201433805
[trace] 2016-7-28 6_22_17_322 ----> archive path:file:///mnt/sdcard/ac_temp/content.zip
[trace] 2016-7-28 6_22_17_339 ----> archive nativePath:/mnt/sdcard/ac_temp/content.zip
[trace] 2016-7-28 6_22_17_359 ----> archive name:content.zip
[trace] 2016-7-28 6_22_17_372 ----> start uncompressing, by [object MobileContentController]
[trace] 2016-7-28 6_22_17_637 ----> zip process started...
[trace] 2016-7-28 6_22_17_653 ----> zip process ERROR: java.io.FileNotFoundException: /mnt/sdcard/ac/pages/page_01.xml: open failed: ENOENT (No such file or directory)
[trace] 2016-7-28 6_22_17_669 ----> zip Progress = 0%
[trace] 2016-7-28 6_22_17_741 ----> [zip process finished]
```

**Comment by varadig** [comment]
With airXZip on the same place is working, but out of memory:

```
[trace] 2016-7-28 6_23_44_250 ----> start download content
[trace] 2016-7-28 6_23_44_271 ----> uncompressed content is not exist
[trace] 2016-7-28 6_23_44_290 ----> zipped content is exist
[trace] 2016-7-28 6_23_44_313 ----> content archive is downloaded!
[trace] 2016-7-28 6_23_44_334 ----> archive size:201433805
[trace] 2016-7-28 6_23_44_350 ----> archive path:file:///mnt/sdcard/ac_temp/content.zip
[trace] 2016-7-28 6_23_44_368 ----> archive nativePath:/mnt/sdcard/ac_temp/content.zip
[trace] 2016-7-28 6_23_44_388 ----> archive name:content.zip
[trace] 2016-7-28 6_23_44_402 ----> start uncompressing, by [object DesktopContentController]
[trace] 2016-7-28 6_23_44_572 ----> file:///mnt/sdcard/ac/pages/page_01.xml
[trace] 2016-7-28 6_23_44_612 ----> file:///mnt/sdcard/ac/pages/page_06.xml
[trace] 2016-7-28 6_23_44_635 ----> file:///mnt/sdcard/ac/pages/page_07.xml
[trace] 2016-7-28 6_23_44_656 ----> file:///mnt/sdcard/ac/pages/page_09.xml
[trace] 2016-7-28 6_23_44_693 ----> file:///mnt/sdcard/ac/pages/page_04.xml
[trace] 2016-7-28 6_23_44_724 ----> file:///mnt/sdcard/ac/pages/page_05.xml
[trace] 2016-7-28 6_23_44_797 ----> file:///mnt/sdcard/ac/pages/page_02.xml
[trace] 2016-7-28 6_23_44_824 ----> file:///mnt/sdcard/ac/pages/page_08.xml
[trace] 2016-7-28 6_23_44_851 ----> file:///mnt/sdcard/ac/pages/page_10.xml
[trace] 2016-7-28 6_23_44_873 ----> file:///mnt/sdcard/ac/pages/page_03.xml
[trace] 2016-7-28 6_23_44_932 ----> file:///mnt/sdcard/ac/media/page10_06.png
[trace] 2016-7-28 6_23_45_0 ----> file:///mnt/sdcard/ac/media/page10_22.png
[trace] 2016-7-28 6_23_45_29 ----> file:///mnt/sdcard/ac/media/page04_01.png
[trace] 2016-7-28 6_23_45_66 ----> file:///mnt/sdcard/ac/media/page10_19.png
[trace] 2016-7-28 6_23_45_118 ----> file:///mnt/sdcard/ac/media/page10_17.png
[trace] 2016-7-28 6_23_45_207 ----> file:///mnt/sdcard/ac/media/page07_03.png
[trace] 2016-7-28 6_23_45_254 ----> file:///mnt/sdcard/ac/media/page06_01.png
[trace] 2016-7-28 6_23_45_298 ----> file:///mnt/sdcard/ac/media/page10_04.png
[trace] 2016-7-28 6_23_45_338 ----> file:///mnt/sdcard/ac/media/page07_02.png
[trace] 2016-7-28 6_23_45_642 ----> file:///mnt/sdcard/ac/media/page08_01.mp3
[trace] 2016-7-28 6_23_45_702 ----> file:///mnt/sdcard/ac/media/page07_09.png
[trace] 2016-7-28 6_23_45_741 ----> file:///mnt/sdcard/ac/media/page10_03.png
[trace] 2016-7-28 6_23_45_782 ----> file:///mnt/sdcard/ac/media/page10_13.png
[Fault] exception, information=Error: Error #1000: The system is out of memory.
```

**Comment by myflashlab** [comment]
> With airXZip on the same place is working, but out of memory:

Of course, the main reason we built this ANE is to make sure Air apps won't go out of memory on big zip content.

Anyway, try the following:

1. make sure the ```ac``` folder exists before you start the unzip process
2. check ```/mnt/sdcard/ac/pages/page_01.xml``` in your zip content and see if that file has any content in it? I mean, check if the file is 0 bytes or not?
3. try another zip file and see if that works?

**Comment by varadig** [comment]
It's realy weired, if I make the directory tree, before unzip the content the unzipping is working.
/mnt/sdcard/ac
/mnt/sdcard/ac/pages
/mnt/sdcard/ac/media

So the ane is can't create the directories and subdirectories from the zip?
On iOS is working well, this is just Android issue.

solution opportunity:
How can I read the directory tree from zip with the ane, and pre create the directory tree for the unzipping?

**Comment by myflashlab** [comment]
Actually it should create the tree automatically. that's why I'm suggesting if you test with other zip files... so we can somehow identify the problem. maybe your zip file needs to be reformatted or something. Please first use other zip files and see what happens.

**Comment by varadig** [comment]
Ok, I compressed the content with php ZipArchive.
I try to looking another solution to compress a content to zip.

**Comment by myflashlab** [comment]
using your window/Mac maybe? Just to tets if folder structures are preserved with a test zip file?

**Comment by varadig** [comment]
the php ZipArchive class was the problem. If I compress the content with mac internal archiver, the folder is created end the unzip method is working.

Thanks, I have to search another PHP lib to compress content. Maybe PclZip....

**Comment by varadig** [comment]
For if somebody run the same issue:

The PHP [ZipArchive](http://php.net/manual/en/class.ziparchive.php) is create wrong archive, for this ANE, use [PclZip](http://www.phpconcept.net/pclzip/user-guide/53) library for compress content.
The archive which is created with [PclZip](http://www.phpconcept.net/pclzip/user-guide/53), is perfect uncompressed with ZipManager
