### ISSUE TITLE
Empty Zip file

### ISSUE THREAD

**Issue by webts** [myflashlab/zipManager-ANE#5]
Hi, im trying to use this ANE to Zip a folder of images (or just 1 file) then pass to a share function.
however when I receive the zip file it is only 22bytes and can not be unzipped.

Any ideas what I am doing wrong?
thanks 

This is my basic code 
```
 private function onShareMedia(event:MouseEvent):void {

        if (!zm)
        {
            zm = new ZipManager();
            zm.addEventListener(ZipManagerEvent.START, onStart);
            zm.addEventListener(ZipManagerEvent.ERROR, onError);
            zm.addEventListener(ZipManagerEvent.PROGRESS, onProgress);
            zm.addEventListener(ZipManagerEvent.COMPLETED, onComplete);
        }

        zipFile = File.applicationStorageDirectory.resolvePath("cached_uploads.zip");
        var file:File = File.applicationStorageDirectory.resolvePath("cached_uploads");

        zm.zip(zipFile, file);

    }


    private function onComplete(e:ZipManagerEvent):void
    {
        trace("[zip process finished]");

        doShare(zipFile);
    }
```

**Comment by myflashlab** [comment]
Is this happening on Android or iOS?

If you are trying on Android, make sure you have set the following permission
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

Also make sure your files are where that Android can have access to them for the zip operation. [check here for more information.](https://github.com/myflashlab/zipManager-ANE/blob/master/FD/src/MainFinal.as#L168-L171)

**Comment by webts** [comment]
thanks, I got it working. 
however I'm not seeing any reduction in file size 
I zipped a folder of images (6 images 12.8mb). the zip file comes out at the exact same size

am I missing something?

**Comment by myflashlab** [comment]
Glad it worked. Regarding the zip file size, well, that's out of our hands and the native code is doing that part internally. However, It's very probable that the image files you are zipping can't be compressed more with standard zip methods. You can confirm that by trying to zip text files. you can see that the file size reduces significantly. So, the zip size depends on the content too. In each case, there nothing we can do here :)
