### ISSUE TITLE
Can't unzip downloaded zip in applicationStorageDirectory on Android

### ISSUE THREAD

**Issue by SlavomirDurej** [myflashlab/zipManager-ANE#7]
When downloading a zip file from internet server during runtime and saving it to the File.applicationStorageDirectory and then trying to unzip it , I'm getting java.io.FileNotFoundException .... open failed: ENOENT (No such file or directory) error. 
This works ok on iOS.
When I try to download the file into the File.documentsDirectory and THEN unzip to File.applicationStorageDirectory this works ok, but then I am not able to READ unzipped files at all!
(and again this works fine on iOS) 
tried this on various Android phones with older or newer OS, in different versions of air .. makes no difference.
Any advice?

**Comment by SlavomirDurej** [comment]
nevermind, using airxzip library instead  and it works, unlike your solution, glad I didn't pay for it..

**Comment by zgkaos** [comment]
Hi, I'm having the same exact issue. Any news on this?
