### ISSUE TITLE
unzip with password

### ISSUE THREAD

**Issue by barrowd** [myflashlab/zipManager-ANE#9]
Hi. Any way to unzip a password protected zip with this ANE? (Password is known) If not, do you know of any that can? Thanks

**Comment by myflashlab** [comment]
This is a cool feature to be added. I hope more people would +1 it also so we can consider building it.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
